# Generated by Django 3.1 on 2021-07-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking',
            new_name='cooking_time',
        ),
    ]
